version: '3'
services:
  db:
    build: db/.
    volumes:
      -  ./pgdata:${POSTGRES_PGDATA}
    environment:
      - LANG=${POSTGRES_LANG}
      - LANGUAGE=${POSTGRES_LANGUAGE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${POSTGRES_PGDATA}
  server:
    build: httpServer/.
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${POSTGRES_PGDATA}
